import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected

from application.db import ALEMBIC_INI_PATH


def _config(database_url: str) -> Config:
    config = Config(str(ALEMBIC_INI_PATH))
    config.set_main_option("sqlalchemy.url", database_url)
    return config


def test_upgrading_an_empty_database_to_head_succeeds(database_url: str) -> None:
    config = _config(database_url)

    command.upgrade(config, "head")


def test_every_migration_downgrades_and_upgrades_again(database_url: str) -> None:
    """Each migration's downgrade must undo its upgrade on every supported
    database, not only the one it was written against."""
    config = _config(database_url)
    command.upgrade(config, "head")

    command.downgrade(config, "base")
    command.upgrade(config, "head")


def test_schema_py_has_no_drift_from_the_migrations(database_url: str) -> None:
    """Guards against the exact bug that motivated adding migrations: a
    column added to application/persistence/schema.py without a matching
    migration, which left `alembic upgrade head` producing a database the
    rest of the app could not query.
    """
    config = _config(database_url)
    command.upgrade(config, "head")

    try:
        command.check(config)
    except AutogenerateDiffsDetected as error:
        pytest.fail(
            "schema.py has changes with no matching Alembic migration; run "
            f"`alembic revision --autogenerate -m '...'` in backend/. Detail: {error}"
        )
