"""add compartment_id to observations, events and recommendations

Revision ID: 11f1de818d70
Revises: a85a51a656b7
Create Date: 2026-09-14 16:34:41.666636

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11f1de818d70"
down_revision: str | Sequence[str] | None = "a85a51a656b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("compartment_id", sa.String(), nullable=True))
    op.create_index(op.f("ix_events_compartment_id"), "events", ["compartment_id"], unique=False)
    op.add_column("observations", sa.Column("compartment_id", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_observations_compartment_id"), "observations", ["compartment_id"], unique=False
    )
    op.add_column("recommendations", sa.Column("compartment_id", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_recommendations_compartment_id"),
        "recommendations",
        ["compartment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recommendations_compartment_id"), table_name="recommendations")
    op.drop_column("recommendations", "compartment_id")
    op.drop_index(op.f("ix_observations_compartment_id"), table_name="observations")
    op.drop_column("observations", "compartment_id")
    op.drop_index(op.f("ix_events_compartment_id"), table_name="events")
    op.drop_column("events", "compartment_id")
    # ### end Alembic commands ###
