"""add media captures

Revision ID: 712ead8a2407
Revises: 11f1de818d70
Create Date: 2026-09-14 18:10:49.852742

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "712ead8a2407"
down_revision: str | Sequence[str] | None = "11f1de818d70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_captures",
        sa.Column("capture_id", sa.String(), nullable=False),
        sa.Column("greenhouse_id", sa.String(), nullable=False),
        sa.Column("compartment_id", sa.String(), nullable=True),
        sa.Column("sensor_id", sa.String(), nullable=False),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.Column("modality", sa.String(), nullable=False),
        sa.Column("artifact_uri", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("capture_id"),
    )
    op.create_index(
        op.f("ix_media_captures_compartment_id"), "media_captures", ["compartment_id"], unique=False
    )
    op.create_index(
        op.f("ix_media_captures_greenhouse_id"), "media_captures", ["greenhouse_id"], unique=False
    )
    op.create_index(
        op.f("ix_media_captures_sensor_id"), "media_captures", ["sensor_id"], unique=False
    )
    op.create_index(
        op.f("ix_media_captures_timestamp"), "media_captures", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_media_captures_timestamp"), table_name="media_captures")
    op.drop_index(op.f("ix_media_captures_sensor_id"), table_name="media_captures")
    op.drop_index(op.f("ix_media_captures_greenhouse_id"), table_name="media_captures")
    op.drop_index(op.f("ix_media_captures_compartment_id"), table_name="media_captures")
    op.drop_table("media_captures")
    # ### end Alembic commands ###
