"""add recommendations table

Revision ID: 768f499d556d
Revises: c510f79c3a1a
Create Date: 2026-09-03 11:09:46.891195

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "768f499d556d"
down_revision: str | Sequence[str] | None = "c510f79c3a1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendations",
        sa.Column("recommendation_id", sa.String(), nullable=False),
        sa.Column("simulation_id", sa.String(), nullable=False),
        sa.Column("greenhouse_id", sa.String(), nullable=False),
        sa.Column("simulated_day", sa.Integer(), nullable=False),
        sa.Column("plant_id", sa.String(), nullable=False),
        sa.Column("action_json", sa.String(), nullable=False),
        sa.Column("source_policy", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("evidence_json", sa.String(), nullable=False),
        sa.Column("rejection_reason", sa.String(), nullable=True),
        sa.Column("approved_by", sa.String(), nullable=True),
        sa.Column("executed_by", sa.String(), nullable=True),
        sa.Column("requested_at", sa.String(), nullable=False),
        sa.Column("reviewed_at", sa.String(), nullable=True),
        sa.Column("executed_at", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("recommendation_id"),
    )
    op.create_index(
        op.f("ix_recommendations_greenhouse_id"), "recommendations", ["greenhouse_id"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_plant_id"), "recommendations", ["plant_id"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_simulated_day"), "recommendations", ["simulated_day"], unique=False
    )
    op.create_index(
        op.f("ix_recommendations_simulation_id"), "recommendations", ["simulation_id"], unique=False
    )
    op.create_index(op.f("ix_recommendations_status"), "recommendations", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recommendations_status"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_simulation_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_simulated_day"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_plant_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_greenhouse_id"), table_name="recommendations")
    op.drop_table("recommendations")
    # ### end Alembic commands ###
