"""add compartments to greenhouses

Revision ID: a85a51a656b7
Revises: eb6e69a1034d
Create Date: 2026-09-14 16:32:40.735549

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a85a51a656b7"
down_revision: str | Sequence[str] | None = "eb6e69a1034d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "greenhouses",
        sa.Column("compartments_json", sa.String(), server_default="[]", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("greenhouses", "compartments_json")
    # ### end Alembic commands ###
