"""baseline schema

Revision ID: b2c0cbaf993c
Revises:
Create Date: 2026-09-01 22:26:17.860786

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2c0cbaf993c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "events",
        sa.Column("event_id", sa.String(), nullable=False),
        sa.Column("greenhouse_id", sa.String(), nullable=False),
        sa.Column("plant_id", sa.String(), nullable=True),
        sa.Column("simulated_day", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("parameters_json", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(op.f("ix_events_greenhouse_id"), "events", ["greenhouse_id"], unique=False)
    op.create_index(op.f("ix_events_plant_id"), "events", ["plant_id"], unique=False)
    op.create_index(op.f("ix_events_simulated_day"), "events", ["simulated_day"], unique=False)
    op.create_table(
        "greenhouse_state_snapshots",
        sa.Column("greenhouse_id", sa.String(), nullable=False),
        sa.Column("simulated_day", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.Column("state_json", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("greenhouse_id", "simulated_day"),
    )
    op.create_table(
        "greenhouse_world_snapshots",
        sa.Column("greenhouse_id", sa.String(), nullable=False),
        sa.Column("simulated_day", sa.Integer(), nullable=False),
        sa.Column("world_json", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("greenhouse_id", "simulated_day"),
    )
    op.create_table(
        "greenhouses",
        sa.Column("greenhouse_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("layout_json", sa.String(), nullable=False),
        sa.Column("plants_json", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("current_state_timestamp", sa.String(), nullable=True),
        sa.Column("latest_available_timestamp", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("greenhouse_id"),
    )
    op.create_table(
        "management_traces",
        sa.Column("simulation_id", sa.String(), nullable=False),
        sa.Column("simulated_day", sa.Integer(), nullable=False),
        sa.Column("trace_json", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("simulation_id", "simulated_day"),
    )
    op.create_table(
        "observations",
        sa.Column("observation_id", sa.String(), nullable=False),
        sa.Column("greenhouse_id", sa.String(), nullable=False),
        sa.Column("plant_id", sa.String(), nullable=True),
        sa.Column("simulated_day", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.String(), nullable=False),
        sa.Column("observation_type", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("observation_id"),
    )
    op.create_index(
        op.f("ix_observations_greenhouse_id"), "observations", ["greenhouse_id"], unique=False
    )
    op.create_index(op.f("ix_observations_plant_id"), "observations", ["plant_id"], unique=False)
    op.create_index(
        op.f("ix_observations_simulated_day"), "observations", ["simulated_day"], unique=False
    )
    op.create_table(
        "scenario_configs",
        sa.Column("greenhouse_id", sa.String(), nullable=False),
        sa.Column("config_json", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("greenhouse_id"),
    )
    op.create_table(
        "simulation_definitions",
        sa.Column("simulation_id", sa.String(), nullable=False),
        sa.Column("greenhouse_id", sa.String(), nullable=False),
        sa.Column("scenario_definition", sa.String(), nullable=False),
        sa.Column("start_date", sa.String(), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("step_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("random_seed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("current_step", sa.Integer(), nullable=False),
        sa.Column("total_steps", sa.Integer(), nullable=False),
        sa.Column("management_policy", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("simulation_id"),
    )
    op.create_index(
        op.f("ix_simulation_definitions_greenhouse_id"),
        "simulation_definitions",
        ["greenhouse_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_simulation_definitions_greenhouse_id"), table_name="simulation_definitions"
    )
    op.drop_table("simulation_definitions")
    op.drop_table("scenario_configs")
    op.drop_index(op.f("ix_observations_simulated_day"), table_name="observations")
    op.drop_index(op.f("ix_observations_plant_id"), table_name="observations")
    op.drop_index(op.f("ix_observations_greenhouse_id"), table_name="observations")
    op.drop_table("observations")
    op.drop_table("management_traces")
    op.drop_table("greenhouses")
    op.drop_table("greenhouse_world_snapshots")
    op.drop_table("greenhouse_state_snapshots")
    op.drop_index(op.f("ix_events_simulated_day"), table_name="events")
    op.drop_index(op.f("ix_events_plant_id"), table_name="events")
    op.drop_index(op.f("ix_events_greenhouse_id"), table_name="events")
    op.drop_table("events")
    # ### end Alembic commands ###
