"""add sensors

Revision ID: bf2ec156f6dd
Revises: 712ead8a2407
Create Date: 2026-09-14 18:14:58.694966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf2ec156f6dd"
down_revision: str | Sequence[str] | None = "712ead8a2407"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensors",
        sa.Column("sensor_id", sa.String(), nullable=False),
        sa.Column("greenhouse_id", sa.String(), nullable=False),
        sa.Column("compartment_id", sa.String(), nullable=True),
        sa.Column("hardware_model", sa.String(), nullable=False),
        sa.Column("device_id", sa.String(), nullable=True),
        sa.Column("intrinsics_json", sa.String(), nullable=False),
        sa.Column("nominal_mounting", sa.String(), nullable=True),
        sa.Column("source_type", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("sensor_id"),
    )
    op.create_index(op.f("ix_sensors_compartment_id"), "sensors", ["compartment_id"], unique=False)
    op.create_index(op.f("ix_sensors_greenhouse_id"), "sensors", ["greenhouse_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sensors_greenhouse_id"), table_name="sensors")
    op.drop_index(op.f("ix_sensors_compartment_id"), table_name="sensors")
    op.drop_table("sensors")
    # ### end Alembic commands ###
