"""add action_executor to simulation_definitions

Revision ID: c510f79c3a1a
Revises: b2c0cbaf993c
Create Date: 2026-09-02 00:49:00.993687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c510f79c3a1a"
down_revision: str | Sequence[str] | None = "b2c0cbaf993c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "simulation_definitions",
        sa.Column(
            "action_executor", sa.String(), server_default="SIMULATED_OPERATOR", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("simulation_definitions", "action_executor")
    # ### end Alembic commands ###
