"""add crop to greenhouses

Revision ID: eb6e69a1034d
Revises: 5d1e7a9c2b41
Create Date: 2026-09-11 22:51:44.862415

"""

import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "eb6e69a1034d"
down_revision: str | Sequence[str] | None = "5d1e7a9c2b41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("greenhouses", sa.Column("crop", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("greenhouses", "crop")
    # ### end Alembic commands ###
