from enum import StrEnum


class SourceType(StrEnum):
    SIMULATION = "SIMULATION"
    REAL_SENSORS = "REAL_SENSORS"
    EXTERNAL_API = "EXTERNAL_API"
    IMPORTED_DATA = "IMPORTED_DATA"


class ObservationType(StrEnum):
    SOIL_MOISTURE_PCT = "soil_moisture_pct"
    AIR_TEMPERATURE_C = "air_temperature_c"
    VISIBLE_FRUIT_COUNT = "visible_fruit_count"
    RIPE_FRUIT_COUNT = "ripe_fruit_count"


class EventType(StrEnum):
    WATERING = "WATERING"
    HARVEST = "HARVEST"
    PRUNING = "PRUNING"
    FERTILISATION = "FERTILISATION"
    MANUAL_INSPECTION = "MANUAL_INSPECTION"


class EventSource(StrEnum):
    HUMAN_REPORTED = "HUMAN_REPORTED"
    ROBOT_CONFIRMED = "ROBOT_CONFIRMED"
    CONTROL_SYSTEM = "CONTROL_SYSTEM"
    INFERRED_FROM_OBSERVATIONS = "INFERRED_FROM_OBSERVATIONS"
    SIMULATION = "SIMULATION"


class Provenance(StrEnum):
    OBSERVED = "OBSERVED"
    REPORTED = "REPORTED"
    DETERMINISTICALLY_DERIVED = "DETERMINISTICALLY_DERIVED"
    INFERRED = "INFERRED"


class PlantHealth(StrEnum):
    HEALTHY = "HEALTHY"
    MONITOR = "MONITOR"
    ACTION_REQUIRED = "ACTION_REQUIRED"
    UNKNOWN = "UNKNOWN"
